-- gerado por scripts/generate-seed.mjs — não editar à mão
-- carrega o conteúdo de origem do site para uma base de dados nova
begin;

delete from public.dishes;
delete from public.menu_categories;
delete from public.gallery_images;
delete from public.instagram_posts;
delete from public.intro_images;
delete from public.intro_facts;
delete from public.experience_panels;
delete from public.events;
delete from public.site_settings;

insert into public.site_settings (id, contact, brand, hero, ocean, nav, ticker, hashtags, event_perks, hours, reservations, concept_notice) values (
  'main',
  '{"name":"Palheiro Velho","kind":"Bar de praia","address":"Travessa da Barrinha","locality":"Esmoriz, Ovar","region":"Aveiro, Portugal","phoneLabel":"+351 220 124 331","phone":"+351220124331","email":"palheirovelho@gmail.com","instagram":"palheiro_velho_beach_bar","instagramUrl":"https://www.instagram.com/palheiro_velho_beach_bar/","facebookUrl":"https://www.facebook.com/palheirovelho/","mapsQuery":"Palheiro Velho, Travessa da Barrinha, Esmoriz, Portugal","note":"Bar de praia em Esmoriz, com vista para o mar e espaço exterior."}'::jsonb,
  '{"publicLogo":"https://jf-esmoriz.pt/wp-content/uploads/2021/12/Palheiro-velho.png","publicLogoSource":"https://jf-esmoriz.pt/onde-comer/","assetStatus":"Logótipo público de referência","photoStatus":"Fotografias de referência temporárias — substituir por material autorizado da marca antes de publicar."}'::jsonb,
  '{"videoSources":["https://videos.pexels.com/video-files/9259112/9259112-hd_1920_1080_25fps.mp4","https://videos.pexels.com/video-files/9259112/9259112-hd_1280_720_25fps.mp4"],"poster":"https://images.pexels.com/videos/9259112/beach-cloud-dawn-dusk-9259112.jpeg?auto=format%2Ccompress&cs=tinysrgb&w=1280","posterImage":{"src":"https://images.pexels.com/videos/9259112/beach-cloud-dawn-dusk-9259112.jpeg?auto=format%2Ccompress&cs=tinysrgb&w=1280","width":1920,"height":1080},"posterSrcSet":"https://images.pexels.com/videos/9259112/beach-cloud-dawn-dusk-9259112.jpeg?auto=format%2Ccompress&cs=tinysrgb&w=640 640w, https://images.pexels.com/videos/9259112/beach-cloud-dawn-dusk-9259112.jpeg?auto=format%2Ccompress&cs=tinysrgb&w=960 960w, https://images.pexels.com/videos/9259112/beach-cloud-dawn-dusk-9259112.jpeg?auto=format%2Ccompress&cs=tinysrgb&w=1280 1280w, https://images.pexels.com/videos/9259112/beach-cloud-dawn-dusk-9259112.jpeg?auto=format%2Ccompress&cs=tinysrgb&w=1440 1440w, https://images.pexels.com/videos/9259112/beach-cloud-dawn-dusk-9259112.jpeg?auto=format%2Ccompress&cs=tinysrgb&w=1920 1920w","posterWidth":1920,"posterHeight":1080,"overlay":"https://images.pexels.com/videos/9259112/beach-cloud-dawn-dusk-9259112.jpeg?auto=format%2Ccompress&cs=tinysrgb&w=720","tagline":"Onde o mar encontra a mesa."}'::jsonb,
  '{"wide":{"src":"https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=2000&h=1000","srcSet":"https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1000&h=500 1000w, https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1500&h=750 1500w, https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=2000&h=1000 2000w, https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=3000&h=1500 3000w, https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=4000&h=2000 4000w","width":2000,"height":1000,"alt":""},"mid":{"src":"https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1200&h=900","srcSet":"https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=450 600w, https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=900&h=700 900w, https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1200&h=900 1200w, https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1800&h=1350 1800w, https://images.pexels.com/photos/16427691/pexels-photo-16427691.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=2400&h=1800 2400w","width":1200,"height":900,"alt":""},"line":["TAKE","YOUR","TIME."],"sub":"Um intervalo visual neste conceito, inspirado na relação do espaço com o mar."}'::jsonb,
  '[{"id":"menu","label":"Carta"},{"id":"experiencia","label":"Espaço"},{"id":"galeria","label":"Galeria"},{"id":"eventos","label":"Momentos"},{"id":"contacto","label":"Contacto"}]'::jsonb,
  array['Bar de praia', 'Vista para o mar', 'Mesas exteriores', 'Música ao vivo', 'Brunch', 'Estacionamento', 'Esmoriz · Portugal']::text[],
  array['@palheiro_velho_beach_bar', 'facebook.com/palheirovelho', 'Esmoriz', 'Bar de praia', 'Vista para o mar', 'Música ao vivo', 'Brunch']::text[],
  array['Música ao vivo indicada publicamente', 'Eventos culturais em registo empresarial', 'Eventos desportivos em registo empresarial', 'Disponibilidade a confirmar diretamente']::text[],
  '[{"id":"verao","label":"Terça a domingo","days":["tue","wed","thu","fri","sat","sun"],"open":"12:30","close":"23:00","note":"Horário de referência, a confirmar com a casa antes de publicar."},{"id":"descanso","label":"Segunda","days":["mon"],"open":"","close":"","note":"Encerrado (a confirmar)."}]'::jsonb,
  '{"enabled":true,"maxPeople":12,"slotMinutes":30,"lastSeatingBeforeClose":90,"minLeadHours":2,"horizonDays":60,"confirmation":"Recebemos o seu pedido. A casa confirma por telefone em horário de funcionamento — guarde a referência acima."}'::jsonb,
  ''
);

insert into public.menu_categories (id, label, kicker, blurb, position) values ('entradas', 'Entradas', 'estrutura demonstrativa', 'Categoria a validar pela marca.', 0);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('entradas', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/13677427/pexels-photo-13677427.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 0);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('entradas', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/36183164/pexels-photo-36183164.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 1);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('entradas', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/28559509/pexels-photo-28559509.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 2);
insert into public.menu_categories (id, label, kicker, blurb, position) values ('pratos', 'Pratos', 'estrutura demonstrativa', 'Categoria a validar pela marca.', 1);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('pratos', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/33991134/pexels-photo-33991134.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 0);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('pratos', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/19897851/pexels-photo-19897851.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 1);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('pratos', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/33144661/pexels-photo-33144661.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 2);
insert into public.menu_categories (id, label, kicker, blurb, position) values ('snacks', 'Snacks', 'estrutura demonstrativa', 'Categoria a validar pela marca.', 2);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('snacks', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/19260799/pexels-photo-19260799.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 0);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('snacks', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/16845663/pexels-photo-16845663.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 1);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('snacks', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/29481861/pexels-photo-29481861.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 2);
insert into public.menu_categories (id, label, kicker, blurb, position) values ('brunch', 'Brunch', 'serviço mencionado publicamente', 'Itens e horários a validar pela marca.', 3);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('brunch', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/2227773/pexels-photo-2227773.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 0);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('brunch', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/28962386/pexels-photo-28962386.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 1);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('brunch', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/15043917/pexels-photo-15043917.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 2);
insert into public.menu_categories (id, label, kicker, blurb, position) values ('bebidas', 'Bebidas', 'estrutura demonstrativa', 'Categoria a validar pela marca.', 4);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('bebidas', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/38895542/pexels-photo-38895542.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 0);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('bebidas', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/28525158/pexels-photo-28525158.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 1);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('bebidas', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/3937673/pexels-photo-3937673.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 2);
insert into public.menu_categories (id, label, kicker, blurb, position) values ('cocktails', 'Cocktails', 'estrutura demonstrativa', 'Categoria a validar pela marca.', 5);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('cocktails', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/3320497/pexels-photo-3320497.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 0);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('cocktails', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/2531184/pexels-photo-2531184.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 1);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('cocktails', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/31460176/pexels-photo-31460176.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 2);
insert into public.menu_categories (id, label, kicker, blurb, position) values ('sobremesas', 'Sobremesas', 'estrutura demonstrativa', 'Categoria a validar pela marca.', 6);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('sobremesas', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/17779122/pexels-photo-17779122.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 0);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('sobremesas', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/20352400/pexels-photo-20352400.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 1);
insert into public.dishes (category_id, name, description, price, image, flag, allergens, position) values ('sobremesas', 'Item a confirmar', 'Substituir por nome, descrição, alergénios e preço validados pela equipa do Palheiro Velho.', '—', '{"src":"https://images.pexels.com/photos/19582734/pexels-photo-19582734.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=240&h=240","width":240,"height":240,"alt":"Item a confirmar"}'::jsonb, 'placeholder', '{}'::text[], 2);

insert into public.gallery_images (src, width, height, cap, loc, position) values ('https://images.pexels.com/photos/14661239/pexels-photo-14661239.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=850', 1100, 850, 'Referência de atmosfera', 'substituir por fotografia autorizada', 0);
insert into public.gallery_images (src, width, height, cap, loc, position) values ('https://images.pexels.com/photos/10757734/pexels-photo-10757734.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=850', 1100, 850, 'Referência de atmosfera', 'substituir por fotografia autorizada', 1);
insert into public.gallery_images (src, width, height, cap, loc, position) values ('https://images.pexels.com/photos/36055325/pexels-photo-36055325.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=850', 1100, 850, 'Referência de atmosfera', 'substituir por fotografia autorizada', 2);
insert into public.gallery_images (src, width, height, cap, loc, position) values ('https://images.pexels.com/photos/12645171/pexels-photo-12645171.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=850', 1100, 850, 'Referência de atmosfera', 'substituir por fotografia autorizada', 3);
insert into public.gallery_images (src, width, height, cap, loc, position) values ('https://images.pexels.com/photos/10066114/pexels-photo-10066114.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=850', 1100, 850, 'Referência de atmosfera', 'substituir por fotografia autorizada', 4);
insert into public.gallery_images (src, width, height, cap, loc, position) values ('https://images.pexels.com/photos/36231216/pexels-photo-36231216.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=850', 1100, 850, 'Referência de atmosfera', 'substituir por fotografia autorizada', 5);
insert into public.gallery_images (src, width, height, cap, loc, position) values ('https://images.pexels.com/photos/12941652/pexels-photo-12941652.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=850', 1100, 850, 'Referência de atmosfera', 'substituir por fotografia autorizada', 6);
insert into public.gallery_images (src, width, height, cap, loc, position) values ('https://images.pexels.com/photos/9685877/pexels-photo-9685877.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=850', 1100, 850, 'Referência de atmosfera', 'substituir por fotografia autorizada', 7);

insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/3320497/pexels-photo-3320497.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', 'sm:col-span-2 sm:row-span-2', null, 'foto', 0);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/2531184/pexels-photo-2531184.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', '', null, 'foto', 1);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/38942913/pexels-photo-38942913.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', '', null, 'reel', 2);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/17779122/pexels-photo-17779122.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', 'sm:row-span-2', null, 'foto', 3);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/6073595/pexels-photo-6073595.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', '', null, 'foto', 4);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/9685877/pexels-photo-9685877.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', 'sm:col-span-2', null, 'foto', 5);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/14808642/pexels-photo-14808642.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', '', null, 'foto', 6);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/28843593/pexels-photo-28843593.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', '', null, 'reel', 7);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/10099363/pexels-photo-10099363.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', 'sm:row-span-2', null, 'foto', 8);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/5840411/pexels-photo-5840411.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', '', null, 'foto', 9);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/7938813/pexels-photo-7938813.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', 'sm:col-span-2', null, 'foto', 10);
insert into public.instagram_posts (src, width, height, cap, likes, span, url, kind, position) values ('https://images.pexels.com/photos/6529722/pexels-photo-6529722.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=600&h=600', 600, 600, 'Imagem editorial temporária', 'conceito privado', '', null, 'foto', 11);

insert into public.intro_images (src, width, height, alt, position) values ('https://images.pexels.com/photos/8528125/pexels-photo-8528125.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1000&h=1250', 1000, 1250, 'Fotografia de referência temporária: esplanada junto à praia', 0);
insert into public.intro_images (src, width, height, alt, position) values ('https://images.pexels.com/photos/14808642/pexels-photo-14808642.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=900&h=1200', 900, 1200, 'Fotografia de referência temporária: praia e sombra de palha', 1);
insert into public.intro_images (src, width, height, alt, position) values ('https://images.pexels.com/photos/9119697/pexels-photo-9119697.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=800&h=800', 800, 800, 'Fotografia de referência temporária: construções de palha na praia', 2);

insert into public.intro_facts (k, title, description, position) values ('01', 'Vista para o mar', 'Indicada na página pública associada ao Palheiro Velho.', 0);
insert into public.intro_facts (k, title, description, position) values ('02', 'Mesas exteriores', 'Serviço indicado na página pública associada à marca.', 1);
insert into public.intro_facts (k, title, description, position) values ('03', 'Música ao vivo', 'Divulgada no site público e nas redes sociais da casa.', 2);
insert into public.intro_facts (k, title, description, position) values ('04', 'Brunch', 'Mencionado no site público associado ao espaço.', 3);
insert into public.intro_facts (k, title, description, position) values ('05', 'Estacionamento', 'Disponibilidade indicada na página pública associada ao espaço.', 4);

insert into public.experience_panels (id, label, idx, image, text, meta, position) values ('view', 'Vista', '01', '{"src":"https://images.pexels.com/photos/5851469/pexels-photo-5851469.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=1500","width":1100,"height":1500,"alt":"Vista"}'::jsonb, 'A página pública da marca indica vista para o mar.', 'serviço publicado', 0);
insert into public.experience_panels (id, label, idx, image, text, meta, position) values ('outside', 'Exterior', '02', '{"src":"https://images.pexels.com/photos/33991146/pexels-photo-33991146.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=1500","width":1100,"height":1500,"alt":"Exterior"}'::jsonb, 'A marca indica mesas no espaço exterior.', 'serviço publicado', 1);
insert into public.experience_panels (id, label, idx, image, text, meta, position) values ('music', 'Música', '03', '{"src":"https://images.pexels.com/photos/7502581/pexels-photo-7502581.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=1500","width":1100,"height":1500,"alt":"Música"}'::jsonb, 'Música ao vivo é mencionada no site público e na atividade recente do Facebook.', 'serviço publicado', 2);
insert into public.experience_panels (id, label, idx, image, text, meta, position) values ('brunch', 'Brunch', '04', '{"src":"https://images.pexels.com/photos/3838633/pexels-photo-3838633.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=1500","width":1100,"height":1500,"alt":"Brunch"}'::jsonb, 'O brunch surge referido na página pública associada ao espaço.', 'serviço publicado', 3);
insert into public.experience_panels (id, label, idx, image, text, meta, position) values ('parking', 'Chegar', '05', '{"src":"https://images.pexels.com/photos/7938813/pexels-photo-7938813.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=1100&h=1500","width":1100,"height":1500,"alt":"Chegar"}'::jsonb, 'O site público indica estacionamento para clientes.', 'informação a confirmar', 4);

insert into public.events (id, n, title, description, image, tag, position) values ('live', '01', 'Música ao vivo', 'Serviço referido na página pública associada à casa e em atividade divulgada nas redes sociais.', '{"src":"https://images.pexels.com/photos/7502581/pexels-photo-7502581.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=400&h=533","width":400,"height":533,"alt":"Música ao vivo"}'::jsonb, 'publicado', 0);
insert into public.events (id, n, title, description, image, tag, position) values ('cultural', '02', 'Eventos culturais', 'A organização de eventos culturais consta da atividade empresarial publicada em diretório público.', '{"src":"https://images.pexels.com/photos/1649693/pexels-photo-1649693.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=400&h=533","width":400,"height":533,"alt":"Eventos culturais"}'::jsonb, 'diretório público', 1);
insert into public.events (id, n, title, description, image, tag, position) values ('sports', '03', 'Eventos desportivos', 'A organização de eventos desportivos consta da atividade empresarial publicada em diretório público.', '{"src":"https://images.pexels.com/photos/7938813/pexels-photo-7938813.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=400&h=533","width":400,"height":533,"alt":"Eventos desportivos"}'::jsonb, 'diretório público', 2);
insert into public.events (id, n, title, description, image, tag, position) values ('private', '04', 'Pedido personalizado', 'Contacte a casa para confirmar qualquer formato, disponibilidade e condições antes de planear.', '{"src":"https://images.pexels.com/photos/12645180/pexels-photo-12645180.jpeg?auto=format%2Ccompress&cs=tinysrgb&fit=crop&q=72&w=400&h=533","width":400,"height":533,"alt":"Pedido personalizado"}'::jsonb, 'a confirmar', 3);

commit;
